### Criar consulta (DOCTOR ou NURSE) — 201 Created
# @name createAppointment
POST http://localhost:8080/api/appointments
Authorization: Basic dr.house 123456
Content-Type: application/json

{
  "patientId": "11111111-1111-1111-1111-111111111111",
  "doctorId": "22222222-2222-2222-2222-222222222222",
  "scheduledAt": "2026-12-01T14:00:00Z",
  "notes": "Consulta de rotina"
}

### Conferir Evento
### docker exec medflow-kafka /opt/kafka/bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic medflow.appointment-events --from-beginning --max-messages 1


### Listar consultas do usuário autenticado — 200 OK
GET http://localhost:8080/api/appointments
Authorization: Basic dr.house 123456

### Buscar consulta por id — 200 OK
GET http://localhost:8080/api/appointments/{{createAppointment.response.body.id}}
Authorization: Basic dr.house 123456

### Atualizar consulta (remarcar / mudar status / notas) — 200 OK
PUT http://localhost:8080/api/appointments/{{createAppointment.response.body.id}}
Authorization: Basic dr.house 123456
Content-Type: application/json

{
  "scheduledAt": "2026-12-15T09:30:00Z",
  "status": "CONFIRMED",
  "notes": "Remarcada a pedido do paciente"
}

### Cancelar consulta — 200 OK
PATCH http://localhost:8080/api/appointments/{{createAppointment.response.body.id}}/cancel
Authorization: Basic dr.house 123456


### ================
### Cenários de erro
### ================

### Sem autenticação — 401 Unauthorized
GET http://localhost:8080/api/appointments

### PATIENT tentando criar consulta — 403 Forbidden
POST http://localhost:8080/api/appointments
Authorization: Basic john.doe 123456
Content-Type: application/json

{
  "patientId": "11111111-1111-1111-1111-111111111111",
  "doctorId": "22222222-2222-2222-2222-222222222222",
  "scheduledAt": "2026-12-01T14:00:00Z",
  "notes": "Paciente não pode criar"
}

### Validação: scheduledAt no passado e sem patientId — 400 Bad Request
POST http://localhost:8080/api/appointments
Authorization: Basic dr.house 123456
Content-Type: application/json

{
  "doctorId": "22222222-2222-2222-2222-222222222222",
  "scheduledAt": "2020-01-01T10:00:00Z",
  "notes": "Requisição inválida"
}

### Consulta inexistente — 404 Not Found
GET http://localhost:8080/api/appointments/00000000-0000-0000-0000-000000000000
Authorization: Basic dr.house 123456

### PATIENT consultando suas próprias consultas — 200 OK
GET http://localhost:8080/api/appointments
Authorization: Basic john.doe 123456
