### Listar todo histórico
# @name Appointments
POST http://localhost:8082/graphql
Content-Type: application/json

{
  "query": "{ appointmentHistories { id appointmentId patientName doctorName eventType status scheduledAt recordedAt } }"
}

### Linha do tempo
POST http://localhost:8082/graphql
Content-Type: application/json

{
  "query": "query($appointmentId: ID!) { appointmentHistoryByAppointment(appointmentId: $appointmentId) { eventType status scheduledAt recordedAt } }",
  "variables": { "appointmentId": "{{Appointments.response.body.data.appointmentHistories[0].appointmentId}}" }
}

### Historico de todas as consultas de um paciente
POST http://localhost:8082/graphql
Content-Type: application/json

{
  "query": "query($patientId: ID!) { appointmentHistoriesByPatient(patientId: $patientId) { appointmentId eventType status recordedAt } }",
  "variables": { "patientId": "11111111-1111-1111-1111-111111111111" }
}